baseURL = "https://impact-rio.github.io/handbook"
languageCode = "pt-BR"
title = "Anotações sobre Mechanistic Interpretability em Transformers"

[module]
  [[module.imports]]
    path = "github.com/McShelby/hugo-theme-relearn"

[params]
  author.name = "Ana Carolinha Erthal & Juan Belieni"
  themeVariant = [
  	{ identifier = "zen-auto",  name = "Tema automático", auto = [ "zen-light", "zen-dark" ] },
  	{ identifier = "zen-light", name = "Tema claro"},
  	{ identifier = "zen-dark",  name = "Tema escuro"},
  ]

  editURL = "https://github.com/impact-rio/handbook/edit/main/content/${FilePath}"

  disableSeoHiddenPages = true
  disableRootBreadcrumb = true

  disableInlineCopyToClipBoard = true
  disableHoverBlockCopyToClipBoard = true
  highlightWrap = true

  disableMathJax = false

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.passthrough]
  enable = true

[markup.goldmark.extensions.passthrough.delimiters]
  block = [['$$', '$$']]
  inline = [['$', '$']]

[markup.goldmark.parser.attribute]
  block = true
  title = true
